# from unicodedata import name
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import path 
from  .import views

urlpatterns = [
    path('admin_login/', views.login_view, name='admin_login'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('admin/', views.adminindex, name='admin'),
    # path('logout/',auth_views.LogoutView.as_view(template_name="admin-panel/logout.html"),name="logout"),
    path('logout/',views.logout, name='logout'),
    path('update_logo/', views.update_logo, name='update_logo'),
    path('update_banner/', views.update_banner, name='update_banner'),
    path('update_about/', views.update_about, name='update_about'),
    path('update_contact/', views.update_contact, name='update_contact'),
    path('update_social/', views.update_social, name='update_social'),
    path('add_review/', views.add_review, name='add_review'),
    path('update_privecy_policy/', views.update_privecy_policy, name='update_privecy_policy'),
    path('update_terms_condition/', views.update_terms_condition, name='update_terms_condition'),
    path('update_refund_cancellition/', views.update_refund_cancellition, name='update_refund_cancellition'),
    path('add-blog/', views.add_blog, name='add-blog'),
    path('update-blog/', views.update_all_blog, name='update-blog'),
    path('delete-blog/<int:pk>', views.delete_blog, name='delete_blog'),
    path('update-single-blog/<int:pk>', views.update_single_blog, name='update-single-blog'),
    path('add-event/', views.add_event, name='add-event'),
    path('add_review/',views.add_review,name='add_review'),
    path('add-non-exclusive-brand/',views.add_non_exclusive_brand,name='add_non_exclusive_brand'),
    path('add-non-exclusive-brand/bulk-upload/',views.neb_bulk_upload,name='neb_bulk_upload'),
    path('delete-non-exclusive-brand/',views.delete_non_exclusive_brand,name='delete_non_exclusive_brand'),
    path('update-event/', views.update_all_event, name='update-event'),
    path('update-single-event/<int:pk>', views.update_single_event, name='update-single-event'),
    path('update_single_pre_event/<int:ppk>', views.update_single_pre_event, name='update_single_pre_event'),
    path('add_category/', views.add_category, name='add_category'),
    path('update_category/<int:pk>', views.update_category, name='update_category'),
    path('delete-category/', views.delete_category, name='delete_category'),
    path('add_brand/', views.add_brand, name='add_brand'),
    path('update_brand/<int:bk>', views.update_brand, name='update_brand'),
    path('delete-brand/', views.delete_brand, name='delete_brand'),
    path('update-non-exclusive-brand/<slug:bk>', views.update_non_exclusive_brand, name='update_non_exclusive_brand'),
    path('list_ur_brand_data/',views.list_ur_brand_data,name='list_ur_brand_data'),
    path('single_brand_ur_list/<int:pk>',views.single_brand_ur_list,name='single_brand_ur_list'),
    path('single_invester_list/<int:pk>',views.single_invester_list,name='single_invester_list'),
    path('contact_us_data/',views.contact_us_data,name='contact_us_data'),
    path('contact_us_single_data/<int:pk>',views.contact_us_single_data,name='contact_us_single_data'),
    path('cat_inquery_form_data/<int:ck>',views.cat_inquery_form_data,name='cat_inquery_form_data'),
    path('brand_inquery_form_data/<int:bk>',views.brand_inquery_form_data,name='brand_inquery_form_data'),
    # BOt management
    path('add-bot/',views.add_bot,name='add_bot'),
    path('update-bot/<slug:botslug>',views.update_bot,name='update_bot'),
    path('delete-bot/',views.delete_bot,name='delete_bot'),
     # Articles management 
    path('add-article/',views.add_article,name='add_article'),
    path('delete-article/',views.delete_article,name='delete_article'),
    # Notifications 
    # path('notifications/<int:nfid>',views.show_notification,name='show_notification'),
    path('notifications/',views.show_all_notification,name='show_all_notification'),
    # UAM
    path('add-employee/',views.add_employee,name='add_employee'),
    path('update-employee/<int:userid>',views.update_employee,name='update_employee'),
    path('delete-employee/<int:userid>',views.delete_employee,name='delete_employee'),
    # Approval requests
    path('approval-requests/',views.approval_requests,name='approval_requests'),
    # path('admin-action-on-category/emp/<int:req_id>/<slug:notificationid>',views.admin_action_on_category,name='admin_action_on_category'),

    #fontend urls function path
    path('',views.front_index,name='index'),
    path('about-us',views.front_about,name='about-us'),
    path('privacy_policy',views.front_privacy_policy,name='privacy_policy'),
    path('terms-condition',views.front_term_condition,name='terms-condition'),
    path('refund-and-cancelletion',views.front_refund_cancelletion,name='refund-and-cancelletion'),
    path('category/<slug:pk>',views.front_category,name='front_category'),
    path('brand/<slug:bk>',views.front_brand,name='front_brand'),
    path('front_upcoming_event/<int:id>',views.front_upcoming_event,name='front_upcoming_event'),
    path('blog/<slug:blk>',views.front_single_blog,name='front_single_blog'),
    path('franchise-directory/',views.franchise_directory,name='franchise_directory'),
    path('all_bussiness_opp/',views.all_bussiness_opp,name='all_bussiness_opp'),
    path('all_featured_brands/',views.all_featured_brands,name='all_featured_brands'),
    path('all_food_beverages/',views.all_food_beverages,name='all_food_beverages'),
    path('list_your_brand/',views.list_your_brand,name='list_your_brand'),
    path('become_an_investor/',views.become_an_investor,name='become_an_investor'),
    path('contact/',views.contact,name='contact'),
    path('create_note/', views.createNote, name="note" ),   
    path('consultancy/', views.consultancy_form, name="consultancy" ),
    path('newsletter_form/', views.newsletter_form, name="newsletter_form" ),
    path('dir-inquery-form/', views.dir_inquery_form, name="dir_inquery_form"),
    path('test', views.test, name="asjdh"),
    path('export-form-to-excel', views.export_form_data_view, name="export_form_to_excel"),
    # path('testpage/', views.testpage, name="testpagetestpage" ),
    
    # APIs
    path('api/brand/',views.BrandAPIview.as_view(),name='brand_api'),
    path('api/category/',views.CategoryAPIview.as_view(),name='category_api'),
]