"""
Django settings for FB project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#importing env file
dotenv_path = os.path.join(BASE_DIR, ".env")
load_dotenv(dotenv_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^l3*#y&=!mfir^cx4$@q@100mrxv9$hx(_*c5_ox&o6*i7s79v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1','www.franchisebrigade.com','3.12.129.240']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fbapp',
    # 'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates/',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'fbapp.context_processors.loadBots',
                'fbapp.context_processors.loadNotifications',
                'fbapp.context_processors.loadUserData',
                'fbapp.context_processors.loadSiteData',
            ],
        },
    },
]

WSGI_APPLICATION = 'FB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'ux9_site',
        'HOST':'ux9-new-dev.ce4hgbmsodad.us-east-1.rds.amazonaws.com',
        'PORT':5432,
        'USER':'postgres',
        'PASSWORD':'UX9postgres',
        }
}




# cache configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX":"fb_production"
    }
}

# Cache time to live is 24 hour
CACHE_TTL = 60 * 60 * 12

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
# CKEDITOR_CONFIGS = {
#     'awesome_ckeditor': {
#         'toolbar': 'Basic',
#     },
# }
STATIC_URL = 'static/'
STATIC_DIR=os.path.join(BASE_DIR,'static')

STATIC_ROOT='static_files'

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')
STATICFILES_DIRS=[
    STATIC_DIR,
]

LOGIN_REDIRECT_URL='admin'
LOGIN_URL='admin_login'

CSRF_TRUSTED_ORIGINS = ['https://www.franchisebrigade.com','https://franchisebrigade.com','http://3.12.129.240']
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL CONFIGURATION
EMAIL_HOST ='smtp.gmail.com'
EMAIL_PORT='587'
EMAIL_HOST_USER='testingsender2022@gmail.com'
EMAIL_HOST_PASSWORD='mmovqhtqdfqbqlvz'
EMAIL_USE_TLS=True

# DATA
TOKEN_KEY='qTNdRpKT43ukWUZZWDENmBTZ845wrUUIwnsr4xad3e'
JWT_ALGORITHM=['HS256']
DOMAIN_ADDRS='https://www.franchisebrigade.com'
