# Generated by Django 4.1.3 on 2022-11-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='#', max_length=50)),
                ('mobile', models.BigIntegerField(default='#')),
                ('email', models.EmailField(default='#', max_length=50)),
                ('investment', models.CharField(default='#', max_length=50)),
                ('details', models.TextField(default='#', max_length=50)),
                ('category_id', models.ForeignKey(on_delete=models.deletion.CASCADE, to='fbapp.category')),
            ],
        ),
    ]
