# Generated by Django 4.1.2 on 2023-12-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_banner_image',
            field=models.ImageField(default='#', max_length=500, upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_home_image',
            field=models.ImageField(default='#', max_length=500, upload_to='images/category/'),
        ),
    ]
