# Generated by Django 4.1.2 on 2023-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0002_alter_category_category_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_details',
            name='banner1',
        ),
        migrations.AlterField(
            model_name='about_sec',
            name='about_banner',
            field=models.ImageField(default='#', max_length=500, upload_to='images/about/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_img',
            field=models.ImageField(default='#', max_length=500, upload_to='images/blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='#', max_length=500, upload_to='images/blog/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(default='#', max_length=500, upload_to='images/brand/'),
        ),
        migrations.AlterField(
            model_name='home_details',
            name='banner2',
            field=models.ImageField(default='#', max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home_details',
            name='banner3',
            field=models.ImageField(default='#', max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='home_details',
            name='logo',
            field=models.ImageField(default='#', max_length=500, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='brand_logo',
            field=models.ImageField(default='#', max_length=500, upload_to='images/brand/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(default='#', max_length=500, upload_to='images/review/'),
        ),
        migrations.AlterField(
            model_name='temp_blog',
            name='blog_image',
            field=models.ImageField(default='#', max_length=500, upload_to='images/blog/'),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_logo',
            field=models.ImageField(default='#', max_length=500, upload_to='images/brand/'),
        ),
        migrations.AlterField(
            model_name='temp_category',
            name='category_banner_image',
            field=models.ImageField(default='#', max_length=500, upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='temp_category',
            name='category_home_image',
            field=models.ImageField(default='#', max_length=500, upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='temp_nonexclusivebrands',
            name='brand_logo',
            field=models.ImageField(default='#', max_length=500, upload_to='images/brand/'),
        ),
    ]
