# Generated by Django 4.1.3 on 2022-11-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0004_alter_contact_us_details_alter_contact_us_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='#', max_length=50)),
                ('mobile', models.BigIntegerField(default='#')),
                ('email', models.EmailField(default='#', max_length=50)),
                ('investment', models.CharField(default='#', max_length=50)),
                ('details', models.CharField(default='#', max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
    ]
