# Generated by Django 4.1.2 on 2022-11-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0005_contactus_delete_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_inquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='#', max_length=50)),
                ('lastName', models.CharField(default='#', max_length=50)),
                ('phone', models.BigIntegerField(default='#')),
                ('fCategoryEmail', models.EmailField(default='#', max_length=50)),
                ('InvestmentAmount', models.CharField(default='#', max_length=50)),
                ('completeAddress', models.CharField(default='#', max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='brand_inquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='#', max_length=50)),
                ('lastName', models.CharField(default='#', max_length=50)),
                ('phone', models.BigIntegerField(default='#')),
                ('fBrandEmail', models.EmailField(default='#', max_length=50)),
                ('InvestmentAmount', models.CharField(default='#', max_length=50)),
                ('completeAddress', models.CharField(default='#', max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.brand')),
            ],
        ),
    ]
