# Generated by Django 4.1.2 on 2022-11-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0006_cat_inquery_brand_inquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand_inquery',
            old_name='category_id',
            new_name='brand_id',
        ),
    ]
