# Generated by Django 4.1.2 on 2022-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0007_rename_category_id_brand_inquery_brand_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='#', max_length=50)),
                ('phone', models.BigIntegerField(default='#')),
                ('email', models.EmailField(default='#', max_length=50)),
                ('pin', models.IntegerField(default='#')),
                ('message', models.CharField(default='#', max_length=50)),
            ],
        ),
    ]
