# Generated by Django 4.1.2 on 2022-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0008_consultancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='#', max_length=50)),
            ],
        ),
    ]
