# Generated by Django 4.1.3 on 2022-11-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0009_newsletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_ur_brand',
            name='corporate_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list_ur_brand',
            name='headquarter_pincode',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list_ur_brand',
            name='mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
