# Generated by Django 4.1.3 on 2022-11-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0011_alter_list_ur_brand_corporate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_ur_brand',
            name='corporate_number',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
