# Generated by Django 4.1.2 on 2022-12-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0012_alter_list_ur_brand_corporate_number'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
        migrations.CreateModel(
            name='NonExclusiveBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='#', max_length=100)),
                ('brand_logo', models.ImageField(default='#', upload_to='images/brand/')),
                ('brand_outlets', models.BigIntegerField()),
                ('yr_of_establish', models.IntegerField()),
                ('brand_inv_min', models.BigIntegerField()),
                ('brand_inv_min_type', models.CharField(default='#', max_length=50)),
                ('brand_inv_max', models.BigIntegerField()),
                ('brand_inv_max_type', models.CharField(default='#', max_length=50)),
                ('brand_payback_min', models.IntegerField()),
                ('brand_payback_max', models.IntegerField()),
                ('brand_floor_area_min', models.IntegerField()),
                ('brand_floor_area_max', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='dir_inquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='#', max_length=128)),
                ('phone', models.BigIntegerField(default='#')),
                ('email', models.EmailField(default='#', max_length=50)),
                ('InvestmentAmount', models.CharField(default='#', max_length=50)),
                ('completeAddress', models.CharField(default='#', max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.category')),
            ],
        ),
    ]
