# Generated by Django 4.1.2 on 2022-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0013_alter_list_ur_brand_corporate_number_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='dir_inquery',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
        # migrations.AlterField(
        #     model_name='nonexclusivebrands',
        #     name='id',
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
    ]
