# Generated by Django 4.1.2 on 2022-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0014_alter_dir_inquery_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
        # migrations.AlterField(
        #     model_name='nonexclusivebrands',
        #     name='category_id',
        #     field=models.IntegerField(),
        # ),
    ]
