# Generated by Django 4.1.2 on 2022-12-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0015_alter_list_ur_brand_corporate_number_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
        migrations.DeleteModel(
            name='NonExclusiveBrands',
        ),
    ]
