# Generated by Django 4.1.2 on 2022-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0016_alter_list_ur_brand_corporate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonExclusiveBrands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='#', max_length=100)),
                ('category_id', models.IntegerField()),
                ('brand_logo', models.ImageField(default='#', upload_to='images/brand/')),
                ('brand_outlets', models.BigIntegerField()),
                ('yr_of_establish', models.IntegerField()),
                ('brand_inv_min', models.BigIntegerField()),
                ('brand_inv_min_type', models.CharField(default='#', max_length=50)),
                ('brand_inv_max', models.BigIntegerField()),
                ('brand_inv_max_type', models.CharField(default='#', max_length=50)),
                ('brand_payback_min', models.IntegerField()),
                ('brand_payback_max', models.IntegerField()),
                ('brand_floor_area_min', models.IntegerField()),
                ('brand_floor_area_max', models.IntegerField()),
            ],
        ),
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
    ]
