# Generated by Django 4.1.2 on 2022-12-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0018_alter_list_ur_brand_corporate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dir_inquery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('fullname', models.CharField(default='#', max_length=128)),
                ('phone', models.BigIntegerField(default='#')),
                ('email', models.EmailField(default='#', max_length=50)),
                ('InvestmentAmount', models.CharField(default='#', max_length=50)),
                ('completeAddress', models.CharField(default='#', max_length=50)),
            ],
        ),
        # migrations.AlterField(
        #     # model_name='list_ur_brand',
        #     # name='corporate_number',
        #     # field=models.CharField(default='0000000000', max_length=10),
        # ),
    ]
