# Generated by Django 4.1.2 on 2022-12-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0019_dir_inquery_alter_list_ur_brand_corporate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dir_inquery',
            name='brand_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
    ]
