# Generated by Django 4.1.2 on 2023-01-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0021_brand_brand_payback_max_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_payback_max_type',
            field=models.CharField(default='Year', max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_payback_min_type',
            field=models.CharField(default='Year', max_length=50),
        ),
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='brand_payback_max_type',
            field=models.CharField(default='Year', max_length=50),
        ),
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='brand_payback_min_type',
            field=models.CharField(default='Year', max_length=50),
        ),
    ]
