# Generated by Django 4.1.2 on 2023-01-02 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0022_alter_brand_brand_payback_max_type_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
        # migrations.AlterField(
        #     model_name='nonexclusivebrands',
        #     name='category_id',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbapp.category'),
        # ),
    ]
