# Generated by Django 4.1.2 on 2023-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0023_alter_list_ur_brand_corporate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_payback_max_type',
            field=models.CharField(default='year', max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_payback_min_type',
            field=models.CharField(default='year', max_length=50),
        ),
        # migrations.AlterField(
        #     model_name='list_ur_brand',
        #     name='corporate_number',
        #     field=models.CharField(default='0000000000', max_length=10),
        # ),
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='brand_payback_max_type',
            field=models.CharField(default='year', max_length=50),
        ),
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='brand_payback_min_type',
            field=models.CharField(default='year', max_length=50),
        ),
    ]
