# Generated by Django 4.1.3 on 2023-01-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0025_brand_brand_script_brand_brand_seo_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_ur_brand',
            name='corporate_number',
        ),
    ]
