# Generated by Django 4.1.3 on 2023-01-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0026_remove_list_ur_brand_corporate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_ur_brand',
            name='corporate_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
