# Generated by Django 4.1.3 on 2023-01-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0027_list_ur_brand_corporate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dir_inquery',
            name='city',
            field=models.CharField(default='#', max_length=128),
        ),
    ]
