# Generated by Django 4.1.3 on 2023-01-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0028_dir_inquery_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonExclusiveBrands',
        ),
    ]
