# Generated by Django 4.1.3 on 2023-01-04 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0029_delete_nonexclusivebrands'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonExclusiveBrands',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='#', max_length=100)),
                ('category_id', models.IntegerField()),
                ('brand_logo', models.ImageField(default='#', upload_to='images/brand/')),
                ('brand_outlets', models.BigIntegerField()),
                ('yr_of_establish', models.IntegerField()),
                ('brand_inv_min', models.BigIntegerField()),
                ('brand_inv_min_type', models.CharField(default='#', max_length=50)),
                ('brand_inv_max', models.BigIntegerField()),
                ('brand_inv_max_type', models.CharField(default='#', max_length=50)),
                ('brand_payback_min', models.IntegerField()),
                ('brand_payback_min_type', models.CharField(default='year', max_length=50)),
                ('brand_payback_max_type', models.CharField(default='year', max_length=50)),
                ('brand_payback_max', models.IntegerField()),
                ('brand_floor_area_min', models.IntegerField()),
                ('brand_floor_area_max', models.IntegerField()),
                ('brand_show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
