# Generated by Django 4.1.3 on 2023-01-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0030_nonexclusivebrands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonExclusiveBrands',
        ),
    ]
