# Generated by Django 4.1.3 on 2023-01-04 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0032_nonexclusivebrands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='id',
            field=models.TextField(default=uuid.UUID('2877413a-0a11-42ea-b11e-92194ddab8e6'), primary_key=True, serialize=False),
        ),
    ]
