# Generated by Django 4.1.3 on 2023-01-04 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0033_alter_nonexclusivebrands_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dir_inquery',
        ),
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='id',
            field=models.TextField(default=uuid.UUID('44c112ee-1aa2-426e-b01b-47db31c637ec'), primary_key=True, serialize=False),
        ),
    ]
