# Generated by Django 4.1.3 on 2023-01-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0034_delete_dir_inquery_alter_nonexclusivebrands_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='dir_inquery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField()),
                ('brand_id', models.CharField(max_length=1024)),
                ('fullname', models.CharField(default='#', max_length=128)),
                ('phone', models.BigIntegerField(default='#')),
                ('email', models.EmailField(default='#', max_length=50)),
                ('InvestmentAmount', models.CharField(default='#', max_length=50)),
                ('completeAddress', models.CharField(default='#', max_length=50)),
                ('city', models.CharField(default='#', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nonexclusivebrands',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
