# Generated by Django 4.1.3 on 2023-01-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0035_dir_inquery_alter_nonexclusivebrands_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dir_inquery',
            name='brnad_type',
            field=models.CharField(default='eb', max_length=64),
        ),
    ]
