# Generated by Django 4.1.3 on 2023-01-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0036_dir_inquery_brnad_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dir_inquery',
            old_name='brnad_type',
            new_name='brand_type',
        ),
    ]
