# Generated by Django 4.1.3 on 2023-01-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0037_rename_brnad_type_dir_inquery_brand_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonExclusiveBrands',
        ),
    ]
