# Generated by Django 4.1.2 on 2023-01-06 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0039_nonexclusivebrands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_script',
            field=models.FileField(default='#', upload_to='scripts/brand/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['js'])]),
        ),
    ]
