# Generated by Django 4.1.2 on 2023-01-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0040_alter_brand_brand_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_ismasterfranchaise',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_distribution_margin',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_exclusive_city_rights',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_exclusive_region_rights',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_exclusive_state_rights',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_franchise_fee_share',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_investment_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_investment_max_type',
            field=models.CharField(default='#', max_length=5),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_investment_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_investment_min_type',
            field=models.CharField(default='#', max_length=5),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_master_royalty_share',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
