# Generated by Django 4.1.2 on 2023-01-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0041_brand_brand_ismasterfranchaise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_master_fr_fee',
            field=models.BigIntegerField(default=0),
        ),
    ]
