# Generated by Django 4.1.2 on 2023-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0042_alter_brand_brand_master_fr_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Bots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_slug', models.TextField()),
                ('bot_name', models.TextField()),
                ('bot_script', models.TextField(default='#')),
                ('bot_position', models.IntegerField(default=2)),
            ],
        ),
    ]
