# Generated by Django 4.1.2 on 2023-01-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0043_site_bots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_bots',
            name='bot_slug',
            field=models.TextField(unique=True),
        ),
    ]
