# Generated by Django 4.1.2 on 2023-01-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0044_alter_site_bots_bot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_bots',
            name='is_bot_active',
            field=models.IntegerField(default=1),
        ),
    ]
