# Generated by Django 4.1.2 on 2023-01-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0045_site_bots_is_bot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_bots',
            name='bot_display_on',
            field=models.TextField(default='all'),
        ),
    ]
