# Generated by Django 4.1.2 on 2023-01-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0046_site_bots_bot_display_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_bots',
            name='bot_display_on',
        ),
    ]
