# Generated by Django 4.1.2 on 2023-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0047_remove_site_bots_bot_display_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_bots',
            name='id',
        ),
        # migrations.AlterField(
        #     model_name='site_bots',
        #     name='bot_slug',
        #     field=models.TextField(primary_key=True, serialize=False),
        # ),
    ]
