# Generated by Django 4.1.2 on 2023-01-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0048_remove_site_bots_id_alter_site_bots_bot_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site_Bots',
        ),
    ]
