# Generated by Django 4.1.2 on 2023-01-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0049_delete_site_bots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Bots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_slug', models.TextField()),
                ('bot_name', models.TextField()),
                ('bot_script', models.TextField(default='#')),
                ('bot_display_on', models.TextField(default='all')),
                ('bot_position', models.IntegerField(default=2)),
                ('is_bot_active', models.IntegerField(default=1)),
            ],
        ),
    ]
