# Generated by Django 4.1.2 on 2023-01-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0050_site_bots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(default='#', max_length=250)),
                ('article_slug', models.TextField(default='#')),
                ('article_url', models.TextField(default='#')),
                ('article_desc', models.CharField(default='#', max_length=250)),
                ('article_img', models.ImageField(default='#', upload_to='images/blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
