# Generated by Django 4.1.2 on 2023-01-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0051_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(default='#', max_length=250)),
                ('notification_user', models.IntegerField()),
                ('notification_description', models.TextField(default='#')),
                ('notification_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
