# Generated by Django 4.1.2 on 2023-01-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0052_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_url',
            field=models.TextField(default='#'),
        ),
    ]
