# Generated by Django 4.1.2 on 2023-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0053_notifications_notification_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(default=' ', max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(default='#', max_length=10000)),
                ('access', models.TextField(max_length=10000)),
                ('role', models.CharField(default='employee', max_length=10)),
                ('is_verified', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('is_super', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
