# Generated by Django 4.1.2 on 2023-01-19 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0054_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_super',
            new_name='is_superuser',
        ),
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 6, 48, 57, 300904, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
