# Generated by Django 4.1.2 on 2023-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0055_rename_is_super_employee_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset_Password_Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('token', models.TextField(default='#', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField()),
            ],
        ),
    ]
