# Generated by Django 4.1.2 on 2023-01-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0056_reset_password_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reset_password_requests',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reset_password_requests',
            name='email',
            field=models.CharField(default='#', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
