# Generated by Django 4.1.2 on 2023-01-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0057_remove_reset_password_requests_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reset_Password_Requests',
        ),
    ]
