# Generated by Django 4.1.2 on 2023-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0058_delete_reset_password_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset_Password_Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField(default='#', max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField()),
            ],
        ),
    ]
