# Generated by Django 4.1.2 on 2023-01-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0060_temp_blog_temp_category_temp_nonexclusivebrands_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_user',
            new_name='notification_from',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_to',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
