# Generated by Django 4.1.2 on 2023-01-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0061_rename_notification_user_notifications_notification_from_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
