# Generated by Django 4.1.2 on 2023-01-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0062_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(default='#', max_length=250)),
                ('notification_from', models.IntegerField()),
                ('notification_from_role', models.CharField(max_length=16)),
                ('notification_to', models.IntegerField()),
                ('notification_to_role', models.CharField(max_length=16)),
                ('notification_description', models.TextField(default='#')),
                ('notification_url', models.TextField(default='#')),
                ('notification_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
