# Generated by Django 4.1.2 on 2023-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0063_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_blog',
            name='actor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temp_brand',
            name='actor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temp_category',
            name='actor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temp_nonexclusivebrands',
            name='actor',
            field=models.IntegerField(default=0),
        ),
    ]
