# Generated by Django 4.1.2 on 2023-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0064_temp_blog_actor_temp_brand_actor_temp_category_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_keywords',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_script_position',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='category',
            name='category_script',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='category',
            name='category_script_position',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='category',
            name='category_seo_description',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_seo_keywords',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_seo_title',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_script',
            field=models.TextField(default=''),
        ),
    ]
