# Generated by Django 4.1.2 on 2023-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0065_remove_category_category_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_category',
            name='category_script',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='temp_category',
            name='category_script_position',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='temp_category',
            name='category_seo_description',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='temp_category',
            name='category_seo_keywords',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='temp_category',
            name='category_seo_title',
            field=models.TextField(default='#'),
        ),
    ]
