# Generated by Django 4.1.2 on 2023-01-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0066_temp_category_category_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_category',
            name='category_date',
        ),
    ]
