# Generated by Django 4.1.2 on 2023-01-27 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0067_remove_temp_category_category_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField()),
                ('record_name', models.TextField()),
                ('record_category', models.TextField()),
                ('record_data', models.TextField()),
                ('record_deleted_on', models.DateTimeField(default=datetime.datetime(2023, 1, 27, 6, 42, 14, 737125, tzinfo=datetime.timezone.utc))),
                ('record_exists_till', models.DateTimeField(default=datetime.datetime(2023, 2, 11, 6, 42, 14, 737125, tzinfo=datetime.timezone.utc))),
                ('logs', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='temp_brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='temp_brand',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='temp_brand',
            name='brand_script_position',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_about',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_anticipated_percent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_floor_area_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_floor_area_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_fr_cmd_yr',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_fr_fee',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_fr_terms_yr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_inv_max',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_inv_min',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_investment_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_investment_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_op_cmd_yr',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_outlets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_payback_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_payback_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_script',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_whyus',
            field=models.TextField(default='#'),
        ),
    ]
