# Generated by Django 4.1.2 on 2023-01-27 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0069_alter_trashbin_record_deleted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashbin',
            name='record_deleted_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 6, 43, 37, 771751, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trashbin',
            name='record_exists_till',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 6, 43, 37, 771751, tzinfo=datetime.timezone.utc)),
        ),
    ]
