# Generated by Django 4.1.2 on 2023-01-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0070_alter_trashbin_record_deleted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashbin',
            name='record_deleted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trashbin',
            name='record_exists_till',
            field=models.DateTimeField(),
        ),
    ]
