# Generated by Django 4.1.2 on 2023-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0071_alter_trashbin_record_deleted_on_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='trashbin',
        #     name='record_id',
        #     field=models.TextField(),
        # ),
    ]
