# Generated by Django 4.1.2 on 2023-01-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0072_alter_trashbin_record_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrashBin',
        ),
    ]
