# Generated by Django 4.1.2 on 2023-01-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0073_delete_trashbin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.TextField()),
                ('record_name', models.TextField()),
                ('record_category', models.TextField()),
                ('record_data', models.TextField()),
                ('record_deleted_on', models.DateTimeField(auto_now_add=True)),
                ('record_exists_till', models.DateTimeField()),
                ('logs', models.TextField()),
            ],
        ),
    ]
