# Generated by Django 4.1.2 on 2023-01-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0074_trashbin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_blog',
            name='post_date',
        ),
    ]
