# Generated by Django 4.1.2 on 2023-01-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0075_remove_temp_blog_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_ismasterfranchaise',
            field=models.CharField(default='#', max_length=3),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_distribution_margin',
            field=models.CharField(default='#', max_length=3),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_exclusive_city_rights',
            field=models.CharField(default='#', max_length=3),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_exclusive_region_rights',
            field=models.CharField(default='#', max_length=3),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_exclusive_state_rights',
            field=models.CharField(default='#', max_length=3),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_franchise_fee_share',
            field=models.CharField(default='#', max_length=3),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_master_royalty_share',
            field=models.CharField(default='#', max_length=3),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_payback_max_type',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_payback_min_type',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AlterField(
            model_name='temp_brand',
            name='brand_script_position',
            field=models.IntegerField(default=0),
        ),
    ]
