# Generated by Django 4.1.2 on 2023-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0076_alter_temp_brand_brand_ismasterfranchaise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_category',
            name='category_script_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_nonexclusivebrands',
            name='brand_payback_max_type',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AlterField(
            model_name='temp_nonexclusivebrands',
            name='brand_payback_min_type',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
