# Generated by Django 4.1.2 on 2023-01-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0077_alter_temp_category_category_script_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_slug',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='nonexclusivebrands',
            name='brand_slug',
            field=models.TextField(default='#'),
        ),
    ]
