# Generated by Django 4.1.2 on 2023-01-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0078_blog_blog_slug_brand_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_blog',
            name='blog_slug',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='temp_brand',
            name='brand_slug',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='temp_category',
            name='category_slug',
            field=models.TextField(default='#'),
        ),
    ]
