# Generated by Django 4.1.2 on 2023-02-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0080_remove_blog_blog_seo_blog_blog_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_blog',
            name='blog_seo',
        ),
        migrations.AddField(
            model_name='temp_blog',
            name='blog_script',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='temp_blog',
            name='blog_seo_description',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='temp_blog',
            name='blog_seo_keywords',
            field=models.CharField(default='#', max_length=2048),
        ),
        migrations.AddField(
            model_name='temp_blog',
            name='blog_seo_title',
            field=models.TextField(default='#'),
        ),
    ]
