# Generated by Django 4.1.2 on 2023-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0081_remove_temp_blog_blog_seo_temp_blog_blog_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.TextField(default='#'),
        ),
    ]
